'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Message
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DenariuChequeWriterSoft.Message", GetType(Message).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Already Exit.
        '''</summary>
        Friend Shared ReadOnly Property Bank_Already_Exit() As String
            Get
                Return ResourceManager.GetString("Bank_Already_Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Upload Cheque Leaf.
        '''</summary>
        Friend Shared ReadOnly Property Bank_Cheqe_Leaf_Required() As String
            Get
                Return ResourceManager.GetString("Bank_Cheqe_Leaf_Required", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank Successfully Deleted.
        '''</summary>
        Friend Shared ReadOnly Property Bank_Delete() As String
            Get
                Return ResourceManager.GetString("Bank_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want Delete This Record? .
        '''</summary>
        Friend Shared ReadOnly Property Bank_Delete_Record() As String
            Get
                Return ResourceManager.GetString("Bank_Delete_Record", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to Exit?.
        '''</summary>
        Friend Shared ReadOnly Property Bank_Exit() As String
            Get
                Return ResourceManager.GetString("Bank_Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Margin Should Be Positive.
        '''</summary>
        Friend Shared ReadOnly Property Bank_Height_Validate() As String
            Get
                Return ResourceManager.GetString("Bank_Height_Validate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Enter Bank Name.
        '''</summary>
        Friend Shared ReadOnly Property Bank_Name_Required() As String
            Get
                Return ResourceManager.GetString("Bank_Name_Required", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank Successfully Saved.
        '''</summary>
        Friend Shared ReadOnly Property Bank_Save() As String
            Get
                Return ResourceManager.GetString("Bank_Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Margin Should Be Positive.
        '''</summary>
        Friend Shared ReadOnly Property Bank_Width_Validate() As String
            Get
                Return ResourceManager.GetString("Bank_Width_Validate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Already Exit.
        '''</summary>
        Friend Shared ReadOnly Property Company_Already_Exit() As String
            Get
                Return ResourceManager.GetString("Company_Already_Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you Delete This Record?.
        '''</summary>
        Friend Shared ReadOnly Property Company_Delete() As String
            Get
                Return ResourceManager.GetString("Company_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company sucessfully Deleted.
        '''</summary>
        Friend Shared ReadOnly Property Company_Delete_After() As String
            Get
                Return ResourceManager.GetString("Company_Delete_After", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to Exit?.
        '''</summary>
        Friend Shared ReadOnly Property Company_Exit() As String
            Get
                Return ResourceManager.GetString("Company_Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company Created Successfully.{0}{0} Login Details: {0}  User Id = admin {0}  Password =admin.
        '''</summary>
        Friend Shared ReadOnly Property Company_Inserted() As String
            Get
                Return ResourceManager.GetString("Company_Inserted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Enter Company Name.
        '''</summary>
        Friend Shared ReadOnly Property Company_Name_Required() As String
            Get
                Return ResourceManager.GetString("Company_Name_Required", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Enter New Password.
        '''</summary>
        Friend Shared ReadOnly Property Company_New_Password() As String
            Get
                Return ResourceManager.GetString("Company_New_Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old Password is Not Matched.
        '''</summary>
        Friend Shared ReadOnly Property Company_NotMatched() As String
            Get
                Return ResourceManager.GetString("Company_NotMatched", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Enter Old Password.
        '''</summary>
        Friend Shared ReadOnly Property Company_Old_Password() As String
            Get
                Return ResourceManager.GetString("Company_Old_Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Please Enter Confirm Password.
        '''</summary>
        Friend Shared ReadOnly Property Company_Pwd_Conformation() As String
            Get
                Return ResourceManager.GetString("Company_Pwd_Conformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirmation Password is Mismatch.
        '''</summary>
        Friend Shared ReadOnly Property Company_Pwd_Mismatch() As String
            Get
                Return ResourceManager.GetString("Company_Pwd_Mismatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company Successfully Saved.
        '''</summary>
        Friend Shared ReadOnly Property Company_save() As String
            Get
                Return ResourceManager.GetString("Company_save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully Saved.
        '''</summary>
        Friend Shared ReadOnly Property Company_Updated() As String
            Get
                Return ResourceManager.GetString("Company_Updated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to Exit?.
        '''</summary>
        Friend Shared ReadOnly Property Main_Esc_Msg() As String
            Get
                Return ResourceManager.GetString("Main_Esc_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suceessfully Deleted.
        '''</summary>
        Friend Shared ReadOnly Property Payee_Delete() As String
            Get
                Return ResourceManager.GetString("Payee_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you Delete This Record?.
        '''</summary>
        Friend Shared ReadOnly Property Payee_Delete_Record() As String
            Get
                Return ResourceManager.GetString("Payee_Delete_Record", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to Exit?.
        '''</summary>
        Friend Shared ReadOnly Property Payee_Exit() As String
            Get
                Return ResourceManager.GetString("Payee_Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Enter The Name.
        '''</summary>
        Friend Shared ReadOnly Property Payee_Name_Required() As String
            Get
                Return ResourceManager.GetString("Payee_Name_Required", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully Saved.
        '''</summary>
        Friend Shared ReadOnly Property Payee_Saved() As String
            Get
                Return ResourceManager.GetString("Payee_Saved", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
